post {

    success {
        emailext(
            subject: "✅ Deployment Successful | ${env.JOB_NAME} | Build #${env.BUILD_NUMBER}",
            mimeType: 'text/html',
            to: 'bhaveshshankarkallur@gmail.com',
            body: """
<html>
<head>
<style>
body{
    font-family: Arial, Helvetica, sans-serif;
    background:#f4f4f4;
}
.container{
    width:650px;
    margin:auto;
    background:white;
    padding:20px;
    border-radius:8px;
    box-shadow:0 0 8px rgba(0,0,0,0.2);
}
.header{
    background:#28a745;
    color:white;
    padding:15px;
    text-align:center;
    border-radius:5px;
}
table{
    width:100%;
    border-collapse:collapse;
    margin-top:20px;
}
th,td{
    border:1px solid #ddd;
    padding:10px;
    text-align:left;
}
th{
    background:#f2f2f2;
}
.footer{
    margin-top:30px;
    font-size:14px;
    color:#555;
}
</style>
</head>

<body>

<div class="container">

<div class="header">
<h2>🚀 Deployment Successful</h2>
</div>

<p>Hello,</p>

<p>Your application has been successfully built and deployed through the Jenkins CI/CD Pipeline.</p>

<table>

<tr>
<th>Project</th>
<td>${env.JOB_NAME}</td>
</tr>

<tr>
<th>Build Number</th>
<td>#${env.BUILD_NUMBER}</td>
</tr>

<tr>
<th>Deployment Status</th>
<td style="color:green;"><b>SUCCESS ✅</b></td>
</tr>

<tr>
<th>Git Commit</th>
<td>${env.GIT_COMMIT?.take(7)}</td>
</tr>

<tr>
<th>Branch</th>
<td>${env.GIT_BRANCH}</td>
</tr>

<tr>
<th>Deployment Date</th>
<td>${new Date().format("dd MMM yyyy hh:mm:ss a")}</td>
</tr>

<tr>
<th>Jenkins Build</th>
<td>
<a href="${env.BUILD_URL}">
${env.BUILD_URL}
</a>
</td>
</tr>

</table>

<div class="footer">

<p>
This is an automated email generated by the Jenkins CI/CD Pipeline.
</p>

<p>
Regards,<br>
<b>DevOps Team</b>
</p>

</div>

</div>

</body>
</html>
"""
        )
    }

    failure {
        emailext(
            subject: "❌ Deployment Failed | ${env.JOB_NAME} | Build #${env.BUILD_NUMBER}",
            mimeType: 'text/html',
            to: 'bhaveshshankarkallur@gmail.com',
            body: """
<html>
<head>
<style>
body{
    font-family: Arial, Helvetica, sans-serif;
    background:#f4f4f4;
}
.container{
    width:650px;
    margin:auto;
    background:white;
    padding:20px;
    border-radius:8px;
    box-shadow:0 0 8px rgba(0,0,0,0.2);
}
.header{
    background:#dc3545;
    color:white;
    padding:15px;
    text-align:center;
    border-radius:5px;
}
table{
    width:100%;
    border-collapse:collapse;
    margin-top:20px;
}
th,td{
    border:1px solid #ddd;
    padding:10px;
    text-align:left;
}
th{
    background:#f2f2f2;
}
.footer{
    margin-top:30px;
    font-size:14px;
    color:#555;
}
</style>
</head>

<body>

<div class="container">

<div class="header">
<h2>❌ Deployment Failed</h2>
</div>

<p>Hello,</p>

<p>Your Jenkins pipeline execution has failed.</p>

<table>

<tr>
<th>Project</th>
<td>${env.JOB_NAME}</td>
</tr>

<tr>
<th>Build Number</th>
<td>#${env.BUILD_NUMBER}</td>
</tr>

<tr>
<th>Deployment Status</th>
<td style="color:red;"><b>FAILED ❌</b></td>
</tr>

<tr>
<th>Git Commit</th>
<td>${env.GIT_COMMIT?.take(7)}</td>
</tr>

<tr>
<th>Branch</th>
<td>${env.GIT_BRANCH}</td>
</tr>

<tr>
<th>Failure Date</th>
<td>${new Date().format("dd MMM yyyy hh:mm:ss a")}</td>
</tr>

<tr>
<th>Jenkins Build</th>
<td>
<a href="${env.BUILD_URL}">
${env.BUILD_URL}
</a>
</td>
</tr>

</table>

<div class="footer">

<p>
Please review the Jenkins Console Output for more information.
</p>

<p>
Regards,<br>
<b>DevOps Team</b>
</p>

</div>

</div>

</body>
</html>
"""
        )
    }
}